name: Node CI

on: [push, pull_request]

jobs:
  test:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x, 18.x, 20.x]
        os: [ubuntu-latest]

    steps:
    - uses: step-security/harden-runner@v2
      with:
        disable-sudo: true
        egress-policy: audit

    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
        cache: npm

    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test

    - uses: codecov/codecov-action@v3.1.4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
